import { sources, text } from './apis.js';
import { inspectContent } from './analyzer.js';
import { config } from './config.js';
import { loadState, saveState } from './store.js';
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
function names(raw){const s=text(raw);const out=new Set();for(const re of [/\b(?:artist|artista|name|nombre)\s*[:=-]\s*([^\n,|]+)/ig,/@([a-z0-9._-]{2,})/ig]){for(const m of s.matchAll(re)){const n=(m[1]||'').trim();if(n.length>1&&!/madrid|españa|mexico|peru|colombia|chile|argentina|venezuela|bolivia|ecuador|puerto|dominicana|paraguay|uruguay/i.test(n))out.add(n);}}return[...out];}
async function verifiedListeners(artist){/* Spotify's public Web API does not expose monthly listeners. Keep this gate fail-closed. */return{monthly:null,source:null,artist};}
async function events(artist){return config.ticketSites.map(x=>({name:x.name,url:x.search.replace('{artist}',encodeURIComponent(artist))}));}
function alertText(a,c,l,h,e){return `🎯 *ARTISTA DETECTADO EN MADRID*\n\n🎤 *${a}*\n🌎 ${c}\n🎧 Oyentes mensuales verificados: *${l.monthly.toLocaleString()}*\n📍 ${h.ai?.reason||'Evidencia de Madrid'}\n📅 ${h.ai?.date||'No indicada'}\n🎪 ${h.ai?.event||'No indicado'}${h.ai?.venue?` — ${h.ai.venue}`:''}\n\n🎟️ *Fuentes oficiales de entradas*\n${e.map(x=>`• ${x.name}: ${x.url}`).join('\n')}\n\n¿Te interesa este artista? Responde *SÍ* o *NO*.\nSi respondes NO, se borrará el material guardado de este aviso. Si no respondes, se conservará como máximo 7 días.`;}
export async function runScan(sock){const state=await loadState();for(const country of config.countries){const discovery=await sources.tiktokSearch(`${country} artista Madrid`);for(const artist of names(discovery).slice(0,config.scan.maxCandidatesPerCountry)){const key=norm(artist);if(state.artists[key]?.blocked)continue;const listeners=await verifiedListeners(artist);if(!Number.isFinite(listeners.monthly)||listeners.monthly<config.minMonthlyListeners)continue;const results=[];const inputs=[['Instagram',await sources.instagramPosts(artist)],['TikTok',await sources.tiktokSearch(artist)],['SoundCloud',await sources.soundcloudSearch(artist)]];for(const [network,data] of inputs)if(data)results.push(await inspectContent(artist,network,data));const hit=results.find(x=>x.directMadrid||(x.ai?.madrid&&x.ai?.current&&x.ai?.confidence>=0.75));if(!hit)continue;const fingerprint=`${key}:${hit.ai?.date||'now'}:${hit.ai?.event||''}`;if(state.artists[fingerprint]?.sent)continue;const msg=alertText(artist,country,listeners,hit,await events(artist));await sock.sendMessage(config.targetJid,{text:msg});state.artists[fingerprint]={sent:true,createdAt:Date.now(),artist,country,folders:results.map(x=>x.folder)};state.pending[fingerprint]={artist,folders:results.map(x=>x.folder),createdAt:Date.now()};await saveState(state);}}}
export async function answerInterest(sock,msg){const jid=msg.key.remoteJid;if(jid!==config.targetJid)return false;const body=(msg.message?.conversation||msg.message?.extendedTextMessage?.text||'').trim().toLowerCase();if(!/^(si|sí|no|s|n)$/.test(body))return false;const state=await loadState();const pending=Object.entries(state.pending).sort((a,b)=>b[1].createdAt-a[1].createdAt)[0];if(!pending)return false;const [key,item]=pending;if(/^no|^n$/.test(body)){const {deleteCase}=await import('./store.js');for(const f of item.folders)await deleteCase(f);state.artists[key]={...(state.artists[key]||{}),blocked:true,rejectedAt:Date.now()};delete state.pending[key];await saveState(state);await sock.sendMessage(jid,{text:'🗑️ Entendido. He eliminado el material multimedia guardado de este aviso.'});}else{state.artists[key]={...(state.artists[key]||{}),interested:true};delete state.pending[key];await saveState(state);await sock.sendMessage(jid,{text:`⭐ Perfecto. Guardaré el seguimiento de ${item.artist} para avisarte de novedades en Madrid.`});}return true;}
